CREATE DATABASE EXAMENBD;
USE EXAMENNBD;

CREATE TABLE UNIDAD_DIDACTICA
(ID_UNIDAD INT PRIMARY KEY,
ACRONIMO VARCHAR(40), 
TITULO VARCHAR(40), 
EVALUACION VARCHAR(40),
DESCRIPCION VARCHAR(100));

CREATE TABLE ENUNCIADO
(ID_ENUNCIADO INT PRIMARY KEY,
DESCRIPCION VARCHAR(100),
NIVEL ENUM ("ALTA", "MEDIA", "BAJA"),
DISPONIBLE BOOLEAN,
RUTA VARCHAR(100));

CREATE TABLE ASIGNAR
(ID_UNIDAD INT PRIMARY KEY,
ID_UNIDAD INT PRIMARY KEY,
FOREIGN KEY (ID_UNIDAD) REFERENCES UNIDADDIDACTICA (ID_UNIDAD),
FOREIGN KEY (ID_ENUNCIADO) REFERENCES ENUNCIADO (ID_ENUNCIADO));

CREATE TABLE CONVOCATORIA_EXAMEN
(CONVOCATORIA VARCHAR(40),
DESCRIPCION VARCHAR(100),
FECHA DATE,
CURSO VARCHAR(100));







