CREATE DATABASE EXAMENBD;
USE EXAMENBD;

CREATE TABLE UNIDAD_DIDACTICA(
	ID_UNIDAD INT PRIMARY KEY AUTO_INCREMENT,
	ACRONIMO VARCHAR(40), 
	TITULO VARCHAR(40), 
	EVALUACION VARCHAR(40),
	DESCRIPCION TEXT
);

CREATE TABLE ENUNCIADO(
	ID_ENUNCIADO INT PRIMARY KEY AUTO_INCREMENT,
	DESCRIPCION TEXT,
	NIVEL ENUM ("ALTA", "MEDIA", "BAJA"),
	DISPONIBLE BOOLEAN,
	RUTA VARCHAR(100)
);

CREATE TABLE ASIGNAR(
	ID_UNIDAD INT,
    ID_ENUNCIADO INT,
    PRIMARY KEY(ID_UNIDAD, ID_ENUNCIADO),
	FOREIGN KEY (ID_UNIDAD) REFERENCES UNIDAD_DIDACTICA (ID_UNIDAD) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (ID_ENUNCIADO) REFERENCES ENUNCIADO (ID_ENUNCIADO) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONVOCATORIA_EXAMEN(
	ID_CONVOCATORIA_EXAMEN INT PRIMARY KEY AUTO_INCREMENT,
	ID_ENUNCIADO INT,
	CONVOCATORIA VARCHAR(40),
	DESCRIPCION TEXT,
	FECHA DATE,
	CURSO VARCHAR(100),
	FOREIGN KEY (ID_ENUNCIADO) REFERENCES ENUNCIADO (ID_ENUNCIADO) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO UNIDAD_DIDACTICA (ID_UNIDAD, ACRONIMO, TITULO, EVALUACION, DESCRIPCION) VALUES
(1, 'MATH', 'Matemáticas Básicas', 'Examen Final', 'Unidad básica de matemáticas'),
(2, 'PHY', 'Física I', 'Prueba Parcial', 'Introducción a la física');

-- Insert en ENUNCIADO
INSERT INTO ENUNCIADO (ID_ENUNCIADO, DESCRIPCION, NIVEL, DISPONIBLE, RUTA) VALUES
(1, 'Problema de álgebra lineal', 'ALTA', TRUE, '/ruta/algebra1.pdf'),
(2, 'Ejercicio de cinemática', 'MEDIA', TRUE, '/ruta/cinematica1.pdf');

-- Insert en ASIGNAR
INSERT INTO ASIGNAR (ID_UNIDAD, ID_ENUNCIADO) VALUES
(1, 1),
(2, 2);

-- Insert en CONVOCATORIA_EXAMEN
INSERT INTO CONVOCATORIA_EXAMEN (ID_CONVOCATORIA_EXAMEN, CONVOCATORIA, DESCRIPCION, FECHA, CURSO, ID_ENUNCIADO) VALUES
(1, 'Convocatoria 2025-09', 'Examen de septiembre 2025', '2025-09-30', 'Curso 1', 1),
(2, 'Convocatoria 2025-10', 'Examen de octubre 2025', '2025-10-15', 'Curso 2', 2);
