CREATE DATABASE EXAMDB;
USE EXAMDB;

CREATE TABLE UNIT (
    ID_UNIT INT PRIMARY KEY AUTO_INCREMENT,
    ACRONYM VARCHAR(40),
    TITLE VARCHAR(40),
    EVALUATION VARCHAR(40),
    DESCRIPTION TEXT
);

CREATE TABLE STATEMENT (
    ID_STATEMENT INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION TEXT,
    DIFFICULTY ENUM("HIGH", "MEDIUM", "LOW"),
    AVAILABLE BOOLEAN,
    ROUTE VARCHAR(100)
);

CREATE TABLE ASSIGN (
    ID_UNIT INT,
    ID_STATEMENT INT,
    PRIMARY KEY(ID_UNIT, ID_STATEMENT),
    FOREIGN KEY (ID_UNIT) REFERENCES UNIT(ID_UNIT) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_STATEMENT) REFERENCES STATEMENT(ID_STATEMENT) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE EXAM_SESSION (
    ID_EXAM_SESSION INT PRIMARY KEY AUTO_INCREMENT,
    ID_STATEMENT INT,
    SESSION VARCHAR(40),
    DESCRIPTION TEXT,
    DATE DATE,
    COURSE VARCHAR(100),
    FOREIGN KEY (ID_STATEMENT) REFERENCES STATEMENT(ID_STATEMENT) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO UNIT (ID_UNIT, ACRONYM, TITLE, EVALUATION, DESCRIPTION) VALUES
(1, 'MATH', 'Basic Mathematics', 'Final Exam', 'Basic math unit'),
(2, 'PHY', 'Physics I', 'Midterm Test', 'Introduction to physics');

INSERT INTO STATEMENT (ID_STATEMENT, DESCRIPTION, DIFFICULTY, AVAILABLE, ROUTE) VALUES
(1, 'Linear algebra problem', 'HIGH', TRUE, './src/assets/problem1.jpg'),
(2, 'Kinematics exercise', 'MEDIUM', TRUE, './src/assets/problem2.jpg');

INSERT INTO ASSIGN (ID_UNIT, ID_STATEMENT) VALUES
(1, 1),
(2, 2);

INSERT INTO EXAM_SESSION (ID_EXAM_SESSION, SESSION, DESCRIPTION, DATE, COURSE, ID_STATEMENT) VALUES
(1, 'Session 2025-09', 'September 2025 exam', '2025-09-30', 'Course 1', 1),
(2, 'Session 2025-10', 'October 2025 exam', '2025-10-15', 'Course 2', 2);
